

const words = {
    "Aberration": "A deviation from what is normal or expected.",
    "Abhor": "To regard with disgust and hatred.",
    "Acquiesce": "To accept something reluctantly but without protest.",
    "Alacrity": "Brisk and cheerful readiness.",
    "Amiable": "Having or displaying a friendly and pleasant manner.",
    "Apathetic": "Showing or feeling no interest, enthusiasm, or concern.",
    "Apprehensive": "Anxious or fearful that something bad or unpleasant will happen.",
    "Archaic": "Very old or old-fashioned.",
    "Ardent": "Having intense feelings or passionate enthusiasm.",
    "Articulate": "Having or showing the ability to speak fluently and coherently.",
    "Ascetic": "Characterized by severe self-discipline and abstention from all forms of indulgence.",
    "Assiduous": "Showing great care and perseverance.",
    "Avarice": "Extreme greed for wealth or material gain.",
    "Belligerent": "Hostile and aggressive.",
    "Benevolent": "Well-meaning and kindly.",
    "Benign": "Gentle, kind, or harmless in effect.",
    "Boisterous": "Noisy, energetic, and cheerful.",
    "Brazen": "Bold and without shame.",
    "Bucolic": "Relating to the pleasant aspects of the countryside.",
    "Burgeon": "Begin to grow or increase rapidly.",
    "Cacophony": "A harsh, discordant mixture of sounds.",
    "Cajole": "To persuade someone to do something by sustained coaxing or flattery.",
    "Candid": "Truthful and straightforward; frank.",
    "Capricious": "Given to sudden and unaccountable changes of mood or behavior.",
    "Castigate": "Reprimand someone severely.",
    "Cathartic": "Providing psychological relief through the expression of strong emotions.",
    "Choleric": "Bad-tempered or irritable.",
    "Clandestine": "Kept secret or done secretly, especially because illicit.",
    "Cogent": "Clear, logical, and convincing.",
    "Complacent": "Showing smug or uncritical satisfaction with oneself or one's achievements.",
    "Convivial": "Friendly, lively, and enjoyable.",
    "Cynical": "Believing that people are motivated by self-interest; distrustful of human sincerity.",
    "Debilitate": "To make someone weak and infirm.",
    "Deferential": "Showing respect and esteem due to a superior or an elder.",
    "Deleterious": "Causing harm or damage.",
    "Demure": "Reserved, modest, and shy.",
    "Derisive": "Expressing contempt or ridicule.",
    "Despondent": "In low spirits from loss of hope or courage.",
    "Diligent": "Having or showing care and conscientiousness in one's work or duties.",
    "Disparage": "Regard or represent as being of little worth.",
    "Dispassionate": "Not influenced by strong emotion; impartial.",
    "Dogmatic": "Inclined to lay down principles as incontrovertibly true.",
    "Duplicity": "Deceitfulness; double-dealing.",
    "Eclectic": "Deriving ideas, style, or taste from a broad and diverse range of sources.",
    "Egregious": "Outstandingly bad; shocking.",
    "Elucidate": "Make something clear; explain.",
    "Eminent": "Famous and respected within a particular sphere or profession.",
    "Enigmatic": "Difficult to interpret or understand; mysterious.",
    "Ephemeral": "Lasting for a very short time.",
    "Erudite": "Having or showing great knowledge or learning.",
    "Euphoric": "Characterized by or feeling intense excitement or happiness.",
    "Exacerbate": "Make a problem or negative feeling worse.",
    "Exultant": "Triumphantly happy.",
    "Fallacious": "Based on a mistaken belief.",
    "Fervent": "Having or displaying a passionate intensity.",
    "Flippant": "Not showing a serious or respectful attitude.",
    "Fortuitous": "Happening by accident or chance rather than design.",
    "Furtive": "Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble.",
    "Garrulous": "Excessively talkative, especially on trivial matters.",
    "Grandiloquent": "Pompous or extravagant in language, style, or manner, especially in a way that is intended to impress.",
    "Gregarious": "Fond of company; sociable.",
    "Guile": "Sly or cunning intelligence.",
    "Hackneyed": "Lacking significance through having been overused; unoriginal and trite.",
    "Hapless": "Unfortunate and deserving of pity.",
    "Harrowing": "Extremely distressing or agonizing.",
    "Hedonistic": "Engaged in the pursuit of pleasure; sensually self-indulgent.",
    "Idyllic": "Extremely happy, peaceful, or picturesque.",
    "Immutable": "Unchanging over time or unable to be changed.",
    "Impudent": "Not showing due respect for another person; impertinent.",
    "Incessant": "Continuing without pause or interruption.",
    "Indolent": "Wanting to avoid activity or exertion; lazy.",
    "Indomitable": "Impossible to subdue or defeat.",
    "Inept": "Having or showing no skill; clumsy.",
    "Ingenuous": "Innocent and unsuspecting.",
    "Insidious": "Proceeding in a gradual, subtle way, but with harmful effects.",
    "Intermittent": "Occurring at irregular intervals; not continuous or steady.",
    "Intrepid": "Fearless; adventurous.",
    "Inveterate": "Having a particular habit or activity that is long-established and unlikely to change.",
    "Irascible": "Easily provoked to anger.",
    "Jocular": "Fond of or characterized by joking.",
    "Languid": "Displaying or having a disinclination for physical exertion or effort; slow and relaxed.",
    "Loquacious": "Tending to talk a great deal; talkative.",
    "Magnanimous": "Generous or forgiving, especially toward a rival or less powerful person.",
    "Maladroit": "Ineffective or bungling; clumsy.",
    "Malevolent": "Having or showing a wish to do evil to others.",
    "Malleable": "Easily influenced; pliable.",
    "Maverick": "An unorthodox or independent-minded person.",
    "Meander": "To wander at random or aimlessly.",
    "Mercurial": "Subject to sudden or unpredictable changes of mood or mind.",
    "Mitigate": "Make less severe, serious, or painful.",
    "Mundane": "Lacking interest or excitement; dull.",
    "Nefarious": "Wicked or criminal.",
    "Nonchalant": "Feeling or appearing casually calm and relaxed.",
    "Nuance": "A subtle difference in or shade of meaning, expression, or sound.",
    "Obsequious": "Obedient or attentive to an excessive or servile degree.",
    "Obstinate": "Stubbornly refusing to change one's opinion or chosen course of action.",
    "Onerous": "Involving a great deal of effort, trouble, or difficulty.",
    "Opulent": "Ostentatiously rich and luxurious or lavish.",
    "Ostentatious": "Characterized by pretentious or showy display; designed to impress.",
    "Paradigm": "A typical example or pattern of something; a model.",
    "Pernicious": "Having a harmful effect, especially in a gradual or subtle way.",
    "Phlegmatic": "Having an unemotional and stolidly calm disposition.",
    "Poignant": "Evoking a keen sense of sadness or regret.",
    "Pompous": "Affectedly and irritatingly grand, solemn, or self-important.",
    "Punctilious": "Showing great attention to detail or correct behavior.",
    "Querulous": "Complaining in a petulant or whining manner.",
    "Quixotic": "Exceedingly idealistic; unrealistic and impractical.",
    "Rancorous": "Characterized by bitterness or resentment.",
    "Recalcitrant": "Having an obstinately uncooperative attitude toward authority or discipline.",
    "Redolent": "Strongly reminiscent or suggestive of something; having a pleasant odor.",
    "Sagacious": "Having or showing keen mental discernment and good judgment.",
    "Salubrious": "Health-giving; healthy.",
    "Sanguine": "Optimistic or positive, especially in an apparently bad or difficult situation.",
    "Scintillating": "Sparkling or shining brightly; brilliantly and excitingly clever or skillful.",
    "Scrupulous": "Diligent, thorough, and extremely attentive to details.",
    "Secular": "Not connected with religious or spiritual matters.",
    "Serendipity": "The occurrence and development of events by chance in a happy or beneficial way.",
    "Spurious": "Not being what it purports to be; false or fake.",
    "Stoic": "Enduring pain or hardship without showing one's feelings or complaining.",
    "Taciturn": "Reserved or uncommunicative in speech; saying little.",
    "Tangible": "Perceptible by touch; clear and definite.",
    "Tempestuous": "Characterized by strong and turbulent or conflicting emotion.",
    "Tenacious": "Tending to keep a firm hold on something; persistent or determined.",
    "Trepidation": "A feeling of fear or anxiety about something that may happen.",
    "Ubiquitous": "Present, appearing, or found everywhere.",
    "Vacillate": "Alternate or waver between different opinions or actions; be indecisive.",
    "Venerate": "Regard with great respect; revere.",
    "Verbose": "Using or expressed in more words than are needed.",
    "Vociferous": "Vehement or clamorous.",
    "Wistful": "Having or showing a feeling of vague or regretful longing.",
    "Zealous": "Having or showing great energy or enthusiasm in pursuit of a cause or an objective."
  };
  
  export default words;
  